version: "3"

services:
  web_driver:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

  tests:
    build: .
    command: pytest
    depends_on:
      - web_driver
    links:
      - web_driver:driver